# Generated by Django 4.0 on 2022-02-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitobjanri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Janr nomi')),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Kitob nomi')),
                ('description', models.TextField(verbose_name='Kitob xaqida')),
                ('price', models.FloatField(verbose_name='Kitob narxi')),
                ('avtor', models.CharField(max_length=50, verbose_name='Kitob muallifi')),
                ('image', models.ImageField(upload_to='product_image', verbose_name='Kitob rasmi')),
                ('status', models.BooleanField(default=True)),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.kitobjanri')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ('name',),
            },
        ),
    ]
