# Generated by Django 4.0 on 2022-01-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_kitobjanri_name_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
